# Generated by Django 3.2 on 2022-03-09 09:10

from django.db import migrations, models
import macaddress.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='router_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sapid', models.IntegerField(verbose_name=18)),
                ('Hostname', models.CharField(max_length=14)),
                ('Loopback', models.GenericIPAddressField()),
                ('Macaddress', macaddress.fields.MACAddressField(blank=True, integer=True, null=True)),
            ],
        ),
    ]
