# Generated by Django 3.2 on 2022-03-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignmentproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router_details',
            name='Sapid',
            field=models.IntegerField(max_length=18),
        ),
    ]
